name: Deploy to Cloud Run

on: workflow_dispatch

env:
  PROJECT_ID: membership-system-nycpha # Your Google Cloud Project ID
  SERVICE_NAME: membership-system-backend # Name for your Cloud Run service (e.g., your-app-name-backend)
  REGION: us-east4 # The Google Cloud region where you want to deploy (e.g., us-central1, europe-west1)
  ARTIFACT_REGISTRY_REPO: membership-system-images # A name for your Artifact Registry repository (e.g., my-app-images)
  IMAGE_NAME: node-backend # A name for your Docker image within the repository

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # This is crucial for Workload Identity Federation

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        # Replace YOUR_PROJECT_NUMBER, POOL_ID, and PROVIDER_ID with your actual values
        # POOL_ID is likely 'github-actions-pool'
        # PROVIDER_ID is likely 'github-provider'
        workload_identity_provider: 'projects/498521561736/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
        service_account: 'github-actions-deployer@membership-system-nycpha.iam.gserviceaccount.com' # Your service account email

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Artifact Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGION }}-docker.pkg.dev
        username: _json_key
        password: ${{ steps.auth.outputs.access_token }} # Authenticate using the token from Workload Identity Federation

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        # Add other Cloud Run configurations as needed, e.g.:
        # env_vars: |
        #   SUPABASE_URL=${{ secrets.SUPABASE_URL }}
        #   SENTRY_DSN=${{ secrets.SENTRY_DSN }}
        #   LOOPS_API_KEY=${{ secrets.LOOPS_API_KEY }}
        # no_allow_unauthenticated: true # Uncomment if you want to restrict public access
        # min_instances: 0
        # max_instances: 1
